# Generated by Django 5.2 on 2025-05-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("name",)},
        ),
    ]
